### ISSUE TITLE
Why didn’t you include links to other relevant code or projects?

### ISSUE THREAD

**Issue by user-123-coder** [NineAbyss/GLBench#3]
Thank you for sharing your work with the community! I noticed that the project doesn’t include any references or links to other relevant code or projects. 
Could you add links to related projects or codebases that might provide additional value to the users?
Thank you for your time!

**Comment by NineAbyss** [comment]
> Thank you for sharing your work with the community! I noticed that the project doesn’t include any references or links to other relevant code or projects. Could you add links to related projects or codebases that might provide additional value to the users? Thank you for your time!

Thanks for your kind reminder! We have taken your suggestions into consideration and add the link to the original papers and repos. Now you can access them in the **_Acknowledgement_** section of the [`README.md`.](https://github.com/NineAbyss/GLBench/blob/main/README.md) We believe this provides more convenience to the users.
