### ISSUE TITLE
Issues about Requirements.txt

### ISSUE THREAD

**Issue by Tan3364** [NineAbyss/GLBench#6]
Hi, when I installed the all liabraries based on Requirements.txt, I found some versions are wrong, not matching others version. Could you refresh the new requirement file?

**Comment by NineAbyss** [comment]
> Hi, when I installed the all liabraries based on Requirements.txt, I found some versions are wrong, not matching others version. Could you refresh the new requirement file?

Thank you for your interest in our work!
We apologize for the confusion. We have updated the `requirements.txt` file in commit 5257faffd1288c0d91165a47a49861de48ccc91f.
If you encounter any further issues, feel free to contact us!
