### ISSUE TITLE
Ask about updating Bert baseline model

### ISSUE THREAD

**Issue by XTanch** [NineAbyss/GLBench#7]
![Screenshot 2024-10-22 214255](https://github.com/user-attachments/assets/e20e7798-aa43-4c15-ad1a-1f5457b538bf)
Hi, could you update these llm models(Bert, senBert and Roberta)? Now I only saw other chatgpt models instead of them.

**Comment by YanJiangJerry** [comment]
Same question

**Comment by NineAbyss** [comment]
Thank you for your friendly reminder! We update codes in commit 9b7a501aa49808a555e03b31e5c0f194328def3e. You can benchmark LLMs as text classification task now.
For example:
```
cd models/llm/llm_supervised
bash roberta_search.sh`
```
 We also update `README.md` in commit 8fbc9370251baa16445020dbde44dc5da69ad960.
