### ISSUE TITLE
issues for llm folader

### ISSUE THREAD

**Issue by YanJiangJerry** [NineAbyss/GLBench#8]
Hi, it seem like the llm folder (only contains a test python file) is uncompleted and missing many essential code for running models such as llama, could you please update the code?

**Comment by NineAbyss** [comment]
Thank you for your friendly reminder! We update the codes in commit 9b7a501aa49808a555e03b31e5c0f194328def3e. You can use `models/llm/inference.py` to inference by LLMs in zero-shot setting now.
